### ISSUE TITLE
Bash : Unable download installer

### ISSUE THREAD

**Issue by Lajci** [chevereto/vps#10]
After run bash.sh and confirm with enter, script will end up with: 
curl: (22) The requested URL returned error: 400

**Comment by rodber** [comment]
> curl: (22) The requested URL returned error: 400

HTTP 400 stands for "Bad Request", you have to provide a working key, otherwise you get 400. You can try invoking the command directly:

https://github.com/chevereto/vps/blob/3.20/bash.sh#L51

```sh
curl -f -SOJL \
    -X POST -d "nowrap" \
    -H "License: LICENSE_HERE" \
    https://chevereto.com/api/download/3.20
```
