### ISSUE TITLE
Undefined variable $isMariaDB

### ISSUE THREAD

**Issue by KenzoKai** [chevereto/vps#5]
This error is from a fresh installation of Ubuntu 20.04 LTS fully updated. No other modifications done.

I run the install script, put in license, it finishes - it then tries to forward the supplied address to localhost.

I put the IP/TLD in manually (http://url/install) - I'm presented with this error. 

```
Chevere\Exceptions\Core\ErrorException thrown in /var/www/html/app/legacy/install/installer.php:665

# Message [Code #2]
Undefined variable $isMariaDB

# Incident ID:6195a5ba2e5b2

# Time
2021-11-18T01:00:42+00:00 [1637197242]

# Stack trace
------------------------------------------------------------
#0 /var/www/html/app/legacy/routes/install.php:28
require_once()
------------------------------------------------------------
#1 /var/www/html/app/src/Components/Legacy/G/Handler.php:255
Chevereto\Components\Legacy\G\Handler->{closure}()
------------------------------------------------------------
#2 /var/www/html/app/src/Components/Legacy/G/Handler.php:137
Chevereto\Components\Legacy\G\Handler->processRequest()
------------------------------------------------------------
#3 /var/www/html/app/legacy/load/web.php:51
Chevereto\Components\Legacy\G\Handler->__construct()
------------------------------------------------------------
#4 /var/www/html/app/legacy/load/loader.php:261
require_once()
------------------------------------------------------------
#5 /var/www/html/app/legacy/entrypoints/index.php:15
require_once()
------------------------------------------------------------
#6 /var/www/html/index.php:14
require_once()
------------------------------------------------------------

# Server
Linux imagehost 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64
```

I've paid for this upgrade forever ago and have yet to see it work lol...

Also attempted on Ubuntu 20.10, and 18.04 - same result.

update: Also attempted full manual server setup. After knocking through all the errors and dependencies - I arrived at the same error. "Undefined variable $isMariaDB"... lol. 

I think you'd do a lot better to just include a SQL file so we can avoid this installer mess.

**Comment by rodber** [comment]
These are issues present in V4.0.0.beta.2 happening when running non-Docker. You should wait for V4.0.0.beta.3 which addresses all these issues.
